name: Go Tests

on:
  push:
    branches: [ main ]
    tags-ignore: [ 'v*' ]  # 忽略版本标签，避免与release.yml冲突
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        go-version: ['1.19', '1.20', '1.21']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Download dependencies
      run: go mod download
    
    - name: Verify dependencies
      run: go mod verify
    
    - name: Run all tests
      run: go test -v -race -timeout=20m $(go list ./... | grep -v internal/handlers)
    
    - name: Run consistency tests
      run: go test -v -timeout=15m ./internal/handlers -run TestSearchConsistencySample1

  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'  # 只在推送到main分支时构建
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Download dependencies
      run: go mod download
    
    - name: Build for Linux
      run: go build -o stardew-seed-searcher-linux .
    
    - name: Build for Windows
      run: GOOS=windows GOARCH=amd64 go build -o stardew-seed-searcher-windows.exe .
    
    - name: Build for macOS
      run: GOOS=darwin GOARCH=amd64 go build -o stardew-seed-searcher-macos .
    
    - name: Test builds
      run: |
        ./stardew-seed-searcher-linux --help || echo "Linux build successful"
        file stardew-seed-searcher-windows.exe || echo "Windows build successful"
        file stardew-seed-searcher-macos || echo "macOS build successful"
